name: flutter_architecture
description: Clean Architecture + Feature First + Bloc 的 Flutter Enterprise Template。
publish_to: none
version: 0.1.0+1
resolution: workspace

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  api_client:
    path: ../../packages/api_client
  auth:
    path: ../../packages/auth
  core:
    path: ../../packages/core
  design_system:
    path: ../../packages/design_system

  auto_route: ^11.1.0
  dio: ^5.7.0
  flutter_bloc: ^9.1.1
  flutter_hooks: ^0.21.0
  flutter_secure_storage: ^10.3.1
  freezed_annotation: ^3.1.0
  get_it: ^9.2.1
  hooked_bloc: ^1.7.0
  injectable: ^3.0.0
  intl: ^0.20.2
  json_annotation: ^4.12.0
  local_auth: ^3.0.2
  path: ^1.9.0
  package_info_plus: ^10.2.1
  path_provider: ^2.1.4
  rxdart: ^0.28.0
  shared_preferences: ^2.3.2
  firebase_core: ^4.12.1
  firebase_crashlytics: ^5.2.6
  connectivity_plus: ^6.1.5
  drift: ^2.34.2
  drift_flutter: ^0.3.1
  sqlite3: ^3.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  auto_route_generator: ^10.5.0
  build_runner: ^2.15.0
  flutter_lints: ^6.0.0
  freezed: 4.0.0-dev.2
  drift_dev: ^2.34.4
  injectable_generator: ^3.0.2
  json_serializable: ^6.14.0
  flutter_secure_storage_platform_interface: ^2.0.1
  shared_preferences_platform_interface: ^2.4.0
  sqflite: ^2.4.2+1
  sqflite_common_ffi: ^2.4.0+3

flutter:
  generate: true
  uses-material-design: true
